import type { Metadata } from 'next';
import './../globals.css';
import AppLayout from '@templates/AppLayout';
import ReactQueryProvider from '@providers/ReactQueryProvider';
import { Providers } from '../providers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryProvider>
            <Providers>
                <AppLayout>{children}</AppLayout>
            </Providers>
        </ReactQueryProvider>
    );
}
